
The following files are used to initialize python shell environments.


* CPython Interpreter (=pythonrc.py=)

  It is the  file loaded at startup by the  regular python shell. It's
  location is either in =~/.pythonrc.py=,  in a path defined by =$PYTHONSTARTUP=
  environment variable.

  See =man python(1)=


* IPython Shell (=ipython_config.py=) AND (=ipython_qtconsole_config.py=)

  These  are  configuration  for  "default"  profile  in  both
  terminal and qtconsole command line.

  Located in =$IPYTHONDIR/profile_default/=


* Matplotlib (=matplotlibrc=)

  Configuration file for the  python mathematical plot library.  It is
  activated  and confgured  by  default when  ipython  is called  with
  =-pylab= option.

  Loading path order is (1) current dir (2) =.matplotlib/matplotlibrc=

  See http://matplotlib.sourceforge.net/users/customizing.html






* Sage math (=init.sage=) AND (=ipythonrc-sage=)

  =init.sage=  sets up  LaTeX properly  for drawing  graphs  and loads
  packages from my own directory.

  It also sets up MathJax to ignore some complex LaTeX environments so
  that they are managed by the true LaTeX rendering backend.

* PyLint python checker (=pylintrc=)

  Pylint  is an  utility for  checking the  quality and  the style  of
  python code, in order to avoid common problems and pitfalls.
