
The following files are used to initialize python shell environments.

* =pythonrc.py= (CPython interpreter)

  It is the  file loaded at startup by the  regular python shell. It's
  location is either in =~/.pythonrc.py=,  in a path defined by =$PYTHONSTARTUP=
  environment variable.

  See =man python(1)=


* =ipython_config.py= AND =ipython_qtconsole_config.py= (ipython >= 0.11)

  Since ipython 0.11 there more features in configuration files. These
  are  configuration  for  "default"  profile  in  both  terminal  and
  qtconsole command line.

  Located in =$IPYTHON_DIR/profile_default/=


* =matplotlibrc=

  Configuration file for the  python mathematical plot library.  It is
  activated  and confgured  by  default when  ipython  is called  with
  =-pylab= option.

  Loading path order is (1) current dir (2) =.matplotlib/matplotlibrc=

  See http://matplotlib.sourceforge.net/users/customizing.html



* =ipythonrc= AND  =ipy_user_conf.py= (ipython <= 0.10)

  Full featured configuration python program for ipython up to version
  0.10 . Located in =$IPYTHON_DIR=.

  Ipython 0.10 is default in Ubuntu 11.04 and in SageMath 5.0

  Ipython 0.9 is in older SageMath

  Use  the latter  configuration file  as  much as  possible, and  the
  former only  to setup thing which  need to be set  up BEFORE ipython
  starts.


* =init.sage= AND =ipythonrc-sage= (SageMath 4.6-5.0)

  SageMath 4.6-4.7  contain ipython  0.9.1, and SageMath  5.0 contains
  Ipython  0.10.  File  =ipy_user_conf.py=  is enough  for  both.  The
  =ipythonrc= file is instead substituted by a Sage specific version.

  The actual meat is in  =init.sage=, which sets up LaTeX properly for
  drawing graphs and loads packages from my own directory.

  It also sets  up JSMath to pass some LaTeX environments to the LaTeX
  rendering backend (i.e. does not try to typeset them on its own).
