#!/bin/bash


# If not running interactively, don't do anything:
[ -z "$PS1" ] && return

# Update the values of LINES and COLUMNS.
shopt -s checkwinsize

PS1='\u@\h:\w\$ '


# If this is an xterm set the title to user@host:dir
case "$TERM" in
xterm*|rxvt*|eterm*)
    PROMPT_COMMAND='echo -ne "\033]0;${USER}@${HOSTNAME}: ${PWD}\007"'
    ;;

*)
    ;;
esac


## Shell independent enviroment
source ~/remoteshell/shenv-common
