#!/bin/sh
#
# Bash configuration for my remote shells (.bashrc)
#

# This only applies to Terastat cluster
TERABASHRC=/afs/sta.uniroma1.it/system/uenv7/bashrc.common
if [ -f $TERABASHRC ]; then
    source $TERABASHRC
fi

# colors
green="\[\e[1;32m\]"
blue="\[\e[1;34m\]"
red="\[\e[1;31m\]"
reset="\[\e[0m\]"

# Colored return value
function nonzero_return() {
	RET=$?
	if [[ $RET -eq 0 ]]; then
            echo -ne "\033[0;32m$RET\033[0m";
        else
            echo -ne "\033[0;31m$RET\033[0m";
        fi;
}


case "$TERM" in
    "dumb")
        PS1='$ '
        ;;
    xterm*|rxvt*|eterm*)
        PS1="[${green}\h${reset}]${blue}\w${reset} <\`nonzero_return\`>\\$ "
        ;;
    *)
        PS1='$ '
        ;;
esac

export PS1



# {{{ Pager --------------------------------------------------------------------
if type most >/dev/null 2>&1; then
    PAGER=most
else
    PAGER=more
fi
export PAGER


# {{{ Alias --------------------------------------------------------------------
alias ec="emacsclient -t"
alias rm="rm -iv"
alias ls='ls --color=auto'
alias grep='grep --color=auto'
alias fgrep='fgrep --color=auto'
alias egrep='egrep --color=auto'


# {{{ Editor -------------------------------------------------------------------
if type emacs >/dev/null 2>&1; then
    EDITOR="emacs"
    ALTERNATE_EDITOR="nano"
elif type nano >/dev/null 2>&1; then
    EDITOR="nano"
    ALTERNATE_EDITOR="vim"
fi

export EDITOR
export ALTERNATE_EDITOR

# {{{ Local --------------------------------------------------------------------
[ -f ~/.bashrc.local ] && source ~/.bashrc.local
