#+TITLE: Python configuration


* CPython Interpreter (=pythonrc.py=)

  It is the  file loaded at startup by the  regular python shell. It's
  location is either in =~/.pythonrc.py=,  in a path defined by =$PYTHONSTARTUP=
  environment variable.

  See =man python(1)=


* IPython Shell (=ipython/=)

  Configuration profiles for IPython (>6.0).

  To activate that you should either set =IPYTHONDIR= to this path, or
  link this path to =~/.ipython=

  There  are few  files  here  that are  not  under  GIT because  they
  are volatile.


* Matplotlib (=matplotlib/=)

  Configuration file for  the python mathematical plot  library. It is
  activated  and confgured  by  default when  ipython  is called  with
  =-pylab= option.

  To activate that you should either set =MPLCONFIGDIR= to this path, or
  link this path to =~/.matplotlib=

  There  are few  files  here  that are  not  under  GIT because  they
  are volatile.
  Configuration file for the  python mathematical plot library.  It is
  activated  and confgured  by  default when  ipython  is called  with
  =-pylab= option.

  See http://matplotlib.sourceforge.net/users/customizing.html

* Sage math (=init.sage=)

  =init.sage=  sets up  LaTeX properly  for drawing  graphs  and loads
  packages from my own directory.

  It also sets up MathJax to ignore some complex LaTeX environments so
  that they are managed by the true LaTeX rendering backend.

* PyLint python checker (=pylintrc=)

  Pylint  is an  utility for  checking the  quality and  the style  of
  python code, in order to avoid common problems and pitfalls.
